[package]
name = "dtrace_rust"
version = "0.1.0"
authors = ["gcj21@cl.cam.ac.uk"]
links = "dtrace"
build = "build.rs"

[dependencies]
kafka = "0.3.2"
libc = "0.2.0"
fern = "0.3.5"
log = "0.3.6"
time = "0.1.35" 
rustc-serialize = "0.3.19"
docopt = "0.6.80"
