# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.ssh.forward_agent = true
	config.ssh.shell = "sh"
	config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
	config.vm.define "ep1" do |ep1|
		ep1.vm.box = "freebsd/FreeBSD-11.0-RC2"
		ep1.vm.base_mac = "080027D14C66"
		#ep1.vm.network "private_network", type: "dhcp", adapter: 2, virtualbox__intnet: "ddtrace-net" 
		ep1.vm.network "private_network", type: "dhcp",  adapter: 2, name: "vboxnet0" 
		ep1.vm.hostname = "ep1"
	end

	config.vm.define "ep2" do |ep2|
		ep2.vm.box = "freebsd_cadets"
		ep2.vm.base_mac = "0800270779C7"
		#ep1.vm.network "private_network", type: "dhcp", adapter: 2, virtualbox__intnet: "ddtrace-net" 
		ep2.ssh.private_key_path = "/home/gcj21/.ssh/gcj21_ddtrace_passwordless"
		ep2.vm.network "public_network"
		ep2.vm.network "private_network", type: "dhcp",  adapter: 2, name: "vboxnet0", mac: "080027FD1A38",auto_config: false 
		ep2.vm.hostname = "ep2"
		ep2.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--nictype2", "Am79C970A"]
			vb.customize ["modifyvm", :id, "--nicbootprio1", "2"]
			vb.customize ["modifyvm", :id, "--nicbootprio2", "1"]
		end
	end

	config.vm.define "kafka" do |kafka|
		kafka.vm.box = "bento/ubuntu-16.04"
		kafka.vm.base_mac = "080027D14C69"
		#kafka.vm.network "private_network", type: "dhcp", adapter: 2, virtualbox__intnet: "ddtrace-net" 
		kafka.vm.network "private_network", type: "dhcp",  adapter: 2, name: "vboxnet0" 
		kafka.vm.hostname = "kafka"
	end

	config.vm.define "opus" do |opus|
		opus.vm.box = "bento/ubuntu-16.04"
		opus.vm.base_mac = "080027D14C67"
		#opus.vm.network "private_network", type: "dhcp", adapter: 2, virtualbox__intnet: "ddtrace-net" 
		opus.vm.network "private_network", type: "dhcp",  adapter: 2, name: "vboxnet0" 
		opus.vm.hostname = "opus"
	end

	config.vm.provider "virtualbox" do |vb|
		vb.customize ["modifyvm", :id, "--memory", 1024]
		vb.customize ["modifyvm", :id, "--cpus", "1"]
		vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
		vb.customize ["modifyvm", :id, "--audio", "none"]
		vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
		vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.provision "ansible" do |ansible|
		ansible.verbose = "v"
		ansible.playbook = "site.yml"
		ansible.groups = {
                	"management" => ["zookeeper"],
                	"commit_log" => ["kafka"],
			"managed_endpoints" => ["ep1","ep2"]
		}
	end
end
