---
##############################################
#  Valeriy Solovyov <weldpua2008@gmail.com>
##############################################
 - name: Add OpenJDK repository to sources
   become: yes
   apt_repository: repo='ppa:openjdk-r/ppa' state=present update_cache=yes
   when: "openjdk_version == 8"

 - name: Installing openjdk-doc
   become: yes
   apt: name=openjdk-{{ openjdk_version }}-doc state=present update_cache=yes cache_valid_time=8600

 - name: Installing openjdk-jdk
   become: yes
   apt: name=openjdk-{{ openjdk_version }}-jdk state=present update_cache=yes
