---
- include: FreeBSD.yml
  when: ansible_distribution == 'FreeBSD'
 
- name: Install git
  apt: name=git state=present
  become: yes

- name: Install Python pip
  become: yes
  apt: name=python-pip state=present

- name: Upgrade pip
  become: yes
  pip:
    name: pip
    extra_args: --upgrade

- name: Install setuptools
  become: yes
  pip: name=setuptools state=present

- name: Install unzip
  become: yes
  apt: name=unzip state=present

- name: Install cmake 
  become: yes
  apt: name=cmake state=present

- name: Install liblzma-dev 
  become: yes
  apt: name=liblzma-dev state=present

- name: Install libyajl
  become: yes
  apt: name=libyajl-dev state=present

- name: Install Protocol Buffers dependencies
  become: yes
  apt: name={{item}} state=present
  with_items:
    - protobuf-compiler
    - libprotobuf-dev

- name: Install protobuf-compiler
  become: yes
  apt: name=protobuf-compiler state=present

- name: Clone OPUS
  git: repo=git@github.com:cadets/opus.git dest=opus update=yes accept_hostkey=yes version=cadets-rustyd

- name: Build OPUS 
  command: "{{ item }} chdir=opus"
  with_items:
    - ./build.sh
  environment:
    JAVA_HOME: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
    VERSION: 0.0.1
#  notify:
#     Start OPUS
...
