[package]
name = "ddtrace_unix_socket"
version = "0.1.0"
authors = ["Graeme Jenkinson <gcj21@cl.cam.ac.uk>"]

[dependencies]
log = "0.3.6"
lazy_static = "0.2.1"
toml = "0.4"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"

[lib]
name = "ddtrace_unix_socket"
crate-type=["dylib"]
