[package]
name = "ddtrace_tcp"
version = "0.1.0"
authors = ["Graeme Jenkinson <gcj21@cl.cam.ac.uk>"]

[dependencies]
log = "0.3.6"
lazy_static = "0.2.1"
toml = "0.2"
rustc-serialize = "0.3.0"

[lib]
name = "ddtrace_tcp"
crate-type=["dylib"]
